// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjJRXzxH2Fpe0YET1VQVxjhjbS5kp5MnE',
    appId: '1:110839687482:web:4568874ac544ea1ac04803',
    messagingSenderId: '110839687482',
    projectId: 'my-filal-project',
    authDomain: 'my-filal-project.firebaseapp.com',
    storageBucket: 'my-filal-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCtAk3RW-0bDdhx0J2jPUiJSEM_CcaRCw',
    appId: '1:110839687482:android:602d6067a1586832c04803',
    messagingSenderId: '110839687482',
    projectId: 'my-filal-project',
    storageBucket: 'my-filal-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_jYS1cyDXlp5f4JIDTsB7Qctbdl6SkzY',
    appId: '1:110839687482:ios:c44c49e55216f159c04803',
    messagingSenderId: '110839687482',
    projectId: 'my-filal-project',
    storageBucket: 'my-filal-project.firebasestorage.app',
    iosBundleId: 'com.example.finalFaperCoding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_jYS1cyDXlp5f4JIDTsB7Qctbdl6SkzY',
    appId: '1:110839687482:ios:c44c49e55216f159c04803',
    messagingSenderId: '110839687482',
    projectId: 'my-filal-project',
    storageBucket: 'my-filal-project.firebasestorage.app',
    iosBundleId: 'com.example.finalFaperCoding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjJRXzxH2Fpe0YET1VQVxjhjbS5kp5MnE',
    appId: '1:110839687482:web:307d23100bb9d58bc04803',
    messagingSenderId: '110839687482',
    projectId: 'my-filal-project',
    authDomain: 'my-filal-project.firebaseapp.com',
    storageBucket: 'my-filal-project.firebasestorage.app',
  );
}
